In [2]:
import numpy as np
import pandas as pd

### Complete dataset in a table form is called dataframe.

### Single column or single row is known as series.

### Creating DataFrame

In [3]:
# using lists
student_data = [
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
]

pd.DataFrame(student_data,columns=['iq','marks','package'])

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [4]:
# using dicts

student_dict = {
    'name':['nitish','ankit','rupesh','rishabh','amit','ankita'],
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

students = pd.DataFrame(student_dict)
students.set_index('name',inplace=True)
students

          iq  marks  package
name
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0

In [5]:
# using read_csv
movies = pd.read_csv('movies.csv')
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [6]:
ipl = pd.read_csv('ipl-matches.csv')
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

### DataFrame Attributes and Methods

In [7]:
# shape
print(movies.shape)
print(ipl.shape)

(1629, 18)
(950, 20)

In [9]:
# dtypes
print(movies.dtypes)
print("*"*50)
print(ipl.dtypes)

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object
**************************************************
ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [10]:
# index
print(movies.index)
print(ipl.index)

RangeIndex(start=0, stop=1629, step=1)
RangeIndex(start=0, stop=950, step=1)

In [15]:
# columns
print(movies.columns)
print("*"*100)
print(ipl.columns)
print("*"*100)
print(students.columns)

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')
****************************************************************************************************
Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')
****************************************************************************************************
Index(['iq', 'marks', 'package'], dtype='object')

In [16]:
# values: It will return all values present in data(every record is a np array. So whole values becomes a 2-d np array)
print(students.values)
print('*'*100)
print(ipl.values)

[[100  80  10]
 [ 90  70   7]
 [120 100  14]
 [ 80  50   2]
 [  0   0   0]
 [  0   0   0]]
****************************************************************************************************
[[1312200 'Ahmedabad' '2022-05-29' ...
  "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']"
  'CB Gaffaney' 'Nitin Menon']
 [1312199 'Ahmedabad' '2022-05-27' ...
  "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']"
  'CB Gaffaney' 'Nitin Menon']
 [1312198 'Kolkata' '2022-05-25' ...
  "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']"
  'J Madanagopal' 'MA Gough']
 ...
 [335984 'Delhi' '2008-04-19' ...
  "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']"
  'Aleem Dar' 'GA Pratapkumar']
 [335983 'Chandigarh' '2008-04-19' ...
  "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']"
  'MR Benson' 'SL Shastri']
 [335982 'Bangalore' '2008-04-18' ...
  "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']"
  'Asad Rauf' 'RE Koertzen']]

In [17]:
# head and tail
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [18]:
ipl.tail(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [19]:
# sample # it will print random rows from the dataset
ipl.sample(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
35,1304085,Pune,2022-04-26,2022,39,Rajasthan Royals,Royal Challengers Bangalore,"Maharashtra Cricket Association Stadium, Pune",Royal Challengers Bangalore,field,N,Rajasthan Royals,Runs,29.0,NaN,R Parag,"['JC Buttler', 'D Padikkal', 'R Ashwin', 'SV S...","['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...",BNJ Oxenford,KN Ananthapadmanabhan
659,548351,Pune,2012-05-03,2012,45,Pune Warriors,Mumbai Indians,Subrata Roy Sahara Stadium,Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,SL Malinga,"['RV Uthappa', 'JD Ryder', 'MJ Clarke', 'SC Ga...","['JEC Franklin', 'SR Tendulkar', 'RG Sharma', ...",Asad Rauf,S Asnani
318,1082646,Delhi,2017-05-14,2017,56,Delhi Daredevils,Royal Challengers Bangalore,Feroz Shah Kotla,Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,10.0,NaN,HV Patel,"['SV Samson', 'KK Nair', 'SS Iyer', 'RR Pant',...","['CH Gayle', 'Vishnu Vinod', 'V Kohli', 'TM He...",CK Nandan,C Shamshuddin
707,501266,Bangalore,2011-05-22,2011,69,Royal Challengers Bangalore,Chennai Super Kings,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,8.0,NaN,CH Gayle,"['AB de Villiers', 'CH Gayle', 'V Kohli', 'SS ...","['MEK Hussey', 'M Vijay', 'SK Raina', 'S Badri...",K Hariharan,RE Koertzen
704,501269,Mumbai,2011-05-25,2011,Elimination Final,Mumbai Indians,Kolkata Knight Riders,Wankhede Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,4.0,NaN,MM Patel,"['AC Blizzard', 'SR Tendulkar', 'RG Sharma', '...","['G Gambhir', 'JH Kallis', 'SP Goswami', 'MK T...",Asad Rauf,SJA Taufel

In [20]:
# info
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [23]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [24]:
# describe
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [25]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [29]:
# isnull
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [28]:
# duplicated
movies.duplicated().sum()

0

In [30]:
students

          iq  marks  package
name
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0

In [31]:
students.duplicated().sum()

1

In [32]:
# rename
students

          iq  marks  package
name
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0

In [33]:
students.rename(columns={'marks':'percent','package':'lpa'},inplace=True)

In [34]:
students  # without inplace this rename is not a permanent changes

          iq  percent  lpa
name
nitish   100       80   10
ankit     90       70    7
rupesh   120      100   14
rishabh   80       50    2
amit       0        0    0
ankita     0        0    0

### Math Methods

In [35]:
# sum -> axis argument
students.sum(axis=0)

iq         390
percent    300
lpa         33
dtype: int64

### When we apply sum on a dataframe then it will add all series individually(if object then concatenate but if number it will give the sum)

In [36]:
# sum -> axis argument
students.sum(axis=1)

name
nitish     190
ankit      167
rupesh     234
rishabh    132
amit         0
ankita       0
dtype: int64

In [37]:
students.mean(axis=1) # rowwise mean

name
nitish     63.333333
ankit      55.666667
rupesh     78.000000
rishabh    44.000000
amit        0.000000
ankita      0.000000
dtype: float64

In [39]:
students.min()

iq         0
percent    0
lpa        0
dtype: int64

In [40]:
students.max()

iq         120
percent    100
lpa         14
dtype: int64

In [42]:
students.median()

iq         85.0
percent    60.0
lpa         4.5
dtype: float64

In [43]:
students.std()

iq         52.057660
percent    41.952354
lpa         5.787918
dtype: float64

In [41]:
students.var()

iq         2710.0
percent    1760.0
lpa          33.5
dtype: float64

### Selecting cols from a DataFrame

In [44]:
# single cols
movies['title_x']

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: object

In [45]:
type(movies['title_x']) # single column in a dataframe is a series

pandas.core.series.Series

In [46]:
ipl['Venue']

0                Narendra Modi Stadium, Ahmedabad
1                Narendra Modi Stadium, Ahmedabad
2                           Eden Gardens, Kolkata
3                           Eden Gardens, Kolkata
4                        Wankhede Stadium, Mumbai
                          ...
945                                  Eden Gardens
946                              Wankhede Stadium
947                              Feroz Shah Kotla
948    Punjab Cricket Association Stadium, Mohali
949                         M Chinnaswamy Stadium
Name: Venue, Length: 950, dtype: object

In [47]:
# multiple cols
movies[['year_of_release','actors','title_x']] # fancy indexing

,year_of_release,actors,title_x
0,2019,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,Uri: The Surgical Strike
1,2019,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,Battalion 609
2,2019,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,The Accidental Prime Minister (film)
3,2019,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,Why Cheat India
4,2018,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,Evening Shadows
...,...,...,...
1624,2001,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,Tera Mera Saath Rahen
1625,2001,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,Yeh Zindagi Ka Safar
1626,2018,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,Sabse Bada Sukh
1627,2019,Gippy Grewal|Zareen Khan|,Daaka
1628,2011,Fawad Khan|,Humsafar

## If we extract one column from a dataframe then it is a Series
## If we extract multiple column from a dataframe then it is a DataFrame

In [48]:
ipl[['Team1','Team2','WinningTeam']]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

### Selecting rows from a DataFrame

- **iloc** - searches using index positions
- **loc** - searches using index labels

In [ ]:
# single row
movies.iloc[5] # 6th row of data (series)

title_x                                                   Soni (film)
imdb_id                                                     tt6078866
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link                   https://en.wikipedia.org/wiki/Soni_(film)
title_y                                                          Soni
original_title                                                   Soni
is_adult                                                            0
year_of_release                                                  2018
runtime                                                            97
genres                                                          Drama
imdb_rating                                                       7.2
imdb_votes                                                       1595
story               Soni  a young policewoman in Delhi  and her su...
summary             While fighting crimes against women in Delhi  ...
tagline                                                           NaN
actors              Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...
wins_nominations                               3 wins & 5 nominations
release_date                                    18 January 2019 (USA)
Name: 5, dtype: object

In [49]:
# multiple row
movies.iloc[5:15:2]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,NaN,18 January 2019 (India)
9,Thackeray (film),tt7777196,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Thackeray_(film),Thackeray,Thackeray,0,2019,120,Biography|Drama,5.1,2301,Balasaheb Thackrey works as a cartoonist for a...,Biographical account of Shiv Sena Supremo Bal...,NaN,Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...,NaN,25 January 2019 (India)
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
13,Total Dhamaal,tt7639372,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Total_Dhamaal,Total Dhamaal,Total Dhamaal,0,2019,130,Action|Adventure|Comedy,4.3,4817,Total Dhamaal is the third instalment in the D...,A group of people learn about a hidden treasur...,The Wildest Adventure Ever,Ajay Devgn|Madhuri Dixit|Anil Kapoor|Riteish D...,NaN,22 February 2019 (India)

In [ ]:
# fancy indexing
movies.iloc[[0,4,5]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)

In [ ]:
# loc
students

          iq  marks  package
name
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0

In [ ]:
students.loc['nitish']

iq         100
marks       80
package     10
Name: nitish, dtype: int64

In [ ]:
students.loc['nitish':'rishabh':2] # rishab is included

         iq  marks  package
name
nitish  100     80       10
rupesh  120    100       14

## Difference between loc and iloc:
On giving a range, in iloc last item is excluded but in loc last item is included.

In [ ]:
# fancy indexing
students.loc[['nitish','ankita','rupesh']]

         iq  marks  package
name
nitish  100     80       10
ankita    0      0        0
rupesh  120    100       14

In [ ]:
# fancy indexing using iloc on this student data
students.iloc[[0,3,4]] # index 0 and nitish is pointing to same index internally.

          iq  marks  package
name
nitish   100     80       10
rishabh   80     50        2
amit       0      0        0

### Selecting both rows and cols

In [ ]:
movies.iloc[0:3,0:3] # 3 rows, 3 columns

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [ ]:
movies.loc[0:2,'title_x':'poster_path']

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

### Filtering a DataFrame

In [ ]:
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [50]:
# find all the final winners
# mask = ipl['MatchNumber'] == 'Final'
# new_df = ipl[mask]
# new_df[['Season','WinningTeam']]

ipl[ipl['MatchNumber'] == 'Final'][['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [52]:
# how many super over finishes have occured
ipl[ipl['SuperOver'] == 'Y'].shape[0]

14

In [53]:
# how many matches has csk won in kolkata
ipl[(ipl['City'] == 'Kolkata') & (ipl['WinningTeam'] == 'Chennai Super Kings')].shape[0]

5

In [54]:
# toss winner is match winner in percentage
(ipl[ipl['TossWinner'] == ipl['WinningTeam']].shape[0]/ipl.shape[0])*100

51.473684210526315

In [56]:
# movies with rating higher than 8 and votes>10000
movies[(movies['imdb_rating'] > 8) & (movies['imdb_votes'] > 10000)].shape[0]

43

In [57]:
# Action movies with rating higher than 7.5
# mask1 = movies['genres'].str.split('|').apply(lambda x:'Action' in x) # converting series into string to apply split
mask1 = movies['genres'].str.contains('Action') # converting series into string to apply contains function
mask2 = movies['imdb_rating'] > 7.5

movies[mask1 & mask2]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
41,Family of Thakurganj,tt8897986,https://upload.wikimedia.org/wikipedia/en/9/99...,https://en.wikipedia.org/wiki/Family_of_Thakur...,Family of Thakurganj,Family of Thakurganj,0,2019,127,Action|Drama,9.4,895,The film is based on small town of North India...,The film is based on small town of North India...,NaN,Jimmy Sheirgill|Mahie Gill|Nandish Singh|Prana...,NaN,19 July 2019 (India)
84,Mukkabaaz,tt7180544,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mukkabaaz,The Brawler,Mukkabaaz,0,2017,154,Action|Drama|Sport,8.1,5434,A boxer (Shravan) belonging to upper cast tra...,A boxer struggles to make his mark in the boxi...,NaN,Viineet Kumar|Jimmy Sheirgill|Zoya Hussain|Rav...,3 wins & 6 nominations,12 January 2018 (USA)
106,Raazi,tt7098658,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raazi,Raazi,Raazi,0,2018,138,Action|Drama|Thriller,7.8,20289,Hidayat Khan is the son of an Indian freedom f...,A Kashmiri woman agrees to marry a Pakistani a...,An incredible true story,Alia Bhatt|Vicky Kaushal|Rajit Kapoor|Shishir ...,21 wins & 26 nominations,11 May 2018 (USA)
110,Parmanu: The Story of Pokhran,tt6826438,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Parmanu:_The_Sto...,Parmanu: The Story of Pokhran,Parmanu: The Story of Pokhran,0,2018,129,Action|Drama|History,7.7,18292,Captain Ashwat Raina's efforts to turn India i...,Ashwat Raina and his teammates arrive in Pokhr...,1998| India: one secret operation| six Indians...,John Abraham|Boman Irani|Diana Penty|Anuja Sat...,NaN,25 May 2018 (USA)
112,Bhavesh Joshi Superhero,tt6129302,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bhavesh_Joshi_Su...,Bhavesh Joshi Superhero,Bhavesh Joshi Superhero,0,2018,154,Action|Drama,7.6,4928,Bhavesh Joshi Superhero is an action film abou...,The origin story of Bhavesh Joshi an Indian s...,This year| justice will have a new name.,Harshvardhan Kapoor|Priyanshu Painyuli|Ashish ...,2 nominations,1 June 2018 (USA)
169,The Ghazi Attack,tt6299040,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Ghazi_Attack...,The Ghazi Attack,The Ghazi Attack,0,2017,116,Action|Thriller|War,7.6,10332,In 1971 amid rising tensions between India an...,A Pakistani submarine Ghazi plans to secretly...,The war you did not know about,Rana Daggubati|Kay Kay Menon|Atul Kulkarni|Om ...,1 win & 7 nominations,17 February 2017 (USA)
219,Raag Desh (film),tt6080746,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raagdesh,Raag Desh,Raag Desh,0,2017,135,Action|Drama|History,8.3,341,A period film based on the historic 1945 India...,A period film based on the historic 1945 India...,NaN,Kunal Kapoor|Amit Sadh|Mohit Marwah|Kenneth De...,NaN,28 July 2017 (India)
258,Irudhi Suttru,tt5310090,https://upload.wikimedia.org/wikipedia/en/f/fe...,https://en.wikipedia.org/wiki/Saala_Khadoos,Saala Khadoos,Saala Khadoos,0,2016,109,Action|Drama|Sport,7.6,10507,An under-fire boxing coach Prabhu is transfer...,The story of a former boxer who quits boxing f...,NaN,Madhavan|Ritika Singh|Mumtaz Sorcar|Nassar|Rad...,9 wins & 2 nominations,29 January 2016 (USA)
280,Laal Rang,tt5600714,NaN,https://en.wikipedia.org/wiki/Laal_Rang,Laal Rang,Laal Rang,0,2016,147,Action|Crime|Drama,8.0,3741,The friendship of two men is tested when thing...,The friendship of two men is tested when thing...,Every job good or bad| must be done with honesty.,Randeep Hooda|Akshay Oberoi|Rajniesh Duggall|P...,NaN,22 April 2016 (India)
297,Udta Punjab,tt4434004,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Udta_Punjab,Udta Punjab,Udta Punjab,0,2016,148,Action|Crime|Drama,7.8,23995,What on earth can a rock star a migrant labor...,A story that revolves around drug abuse in the...,NaN,Shahid Kapoor|Alia Bhatt|Kareena Kapoor|Diljit...,11 wins & 19 nominations,17 June 2016 (USA)
354,Dangal (film),tt5074352,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dangal_(film),Dangal,Dangal,0,2016,161,Action|Biography|Drama,8.4,131338,Biopic of Mahavir Singh Phogat who taught wre...,Former wrestler Mahavir Singh Phogat and his t...,You think our girls are any lesser than boys?,Aamir Khan|Fatima Sana Shaikh|Sanya Malhotra|S...,23 wins & 4 nominations,21 December 2016 (USA)
362,Bajrangi Bhaijaan,tt3863552,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bajrangi_Bhaijaan,Bajrangi Bhaijaan,Bajrangi Bhaijaan,0,2015,163,Action|Comedy|Drama,8.0,65877,A little mute girl from a Pakistani village ge...,An Indian man with a magnanimous heart takes a...,NaN,Salman Khan|Harshaali Malhotra|Nawazuddin Sidd...,25 wins & 13 nominations,17 July 2015 (USA)
365,Baby (2015 Hindi film),tt3848892,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Baby_(2015_Hindi...,Baby,Baby,0,2015,159,Action|Thriller,8.0,49426,The country is perpetually under threat from t...,An elite counter-intelligence unit learns of a...,History Is Made By Those Who Give A Damn!,Akshay Kumar|Danny Denzongpa|Rana Daggubati|Ta...,1 win,23 January 2015 (India)
393,Detective Byomkesh Bakshy!,tt3447364,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Detective_Byomke...,Detective Byomkesh Bakshy!,Detective Byomkesh Bakshy!,0,2015,139,Action|Mystery|Thriller,7.6,14674,CALCUTTA 1943 A WAR - A MYSTERY - and A DETECT...,While investigating the disappearance of a che...,Expect The Unexpected,Sushant Singh Rajput|Anand Tiwari|Neeraj Kabi|...,NaN,3 April 2015 (USA)
449,Titli (2014 film),tt3019620,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Titli_(2014_film),Titli,Titli,0,2014,116,Action|Drama|Thriller,7.6,3677,In the badlands of Delhi's dystopic underbelly...,A Hindi feature film set in the lower depths o...,Daring| Desireable| Dangerous,Nawazuddin Siddiqui|Niharika Singh|Anil George...,4 wins & 5 nominations,20 June 2014 (USA)
536,Haider (film),tt3390572,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Haider_(film),Haider,Haider,0,2014,160,Action|Crime|Drama,8.1,46912,Vishal Bhardwaj's adaptation of William Shakes...,A young man returns to Kashmir after his fathe...,NaN,Tabu|Shahid Kapoor|Shraddha Kapoor|Kay Kay Men...,28 wins & 24 nominations,2 October 2014 (USA)
589,Vishwaroopam,tt2199711,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Vishwaroop_(Hind...,Vishwaroopam,Vishwaroopam,0,2013,148,Action|Thriller,8.2,38016,Vishwanathan a Kathak dance teacher in New Yo...,When a classical dancer's suspecting wife sets...,NaN,Kamal Haasan|Rahul Bose|Shekhar Kapur|Pooja Ku...,5 wins & 11 nominations,25 January 2013 (India)
625,Madras Cafe,tt2855648,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Madras_Cafe,Madras Cafe,Madras Cafe,0,2013,130,Action|Drama|Thriller,7.7,21393,An Indian Intelligence agent (portrayed by Joh...,An Indian intelligence agent journeys to a war...,NaN,John Abraham|Nargis Fakhri|Raashi Khanna|Praka...,10 wins & 10 nominations,23 August 2013 (India)
668,Paan Singh Tomar (film),tt1620933,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Paan_Singh_Tomar...,Paan Singh Tomar,Paan Singh Tomar,0,2012,135,Action|Biography|Crime,8.2,29994,Paan Singh Tomar is a Hindi-language film bas...,The story of Paan Singh Tomar an Indian athle...,NaN,Irrfan Khan|,10 wins & 11 nominations,2 March 2012 (USA)
693,Gangs of Wasseypur,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseypur,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
694,Gangs of Wasseypur – Part 2,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseyp...,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
982,Jodhaa Akbar,tt0449994,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jodhaa_Akbar,Jodhaa Akbar,Jodhaa Akbar,0,2008,213,Action|Drama|History,7.6,27541,Jodhaa Akbar is a sixteenth century love story...,A sixteenth century love story about a marriag...,NaN,Hrithik Roshan|Aishwarya Rai Bachchan|Sonu Soo...,32 wins & 21 nominations,15 February 2008 (USA)
1039,1971 (2007 film),tt0983990,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/1971_(2007_film),1971,1971,0,2007,160,Action|Drama|War,7.9,1121,Based on true facts the film revolves around ...,Based on true facts the film revolves around ...,Honor the heroes.......,Manoj Bajpayee|Ravi Kishan|Deepak Dobriyal|,1 win,9 March 2007 (India)
1058,Black Friday (2007 film),tt0400234,https://upload.wikimedia.org/wikipedia/en/5/58...,https://en.wikipedia.org/wiki/Black_Friday_(20...,Black Friday,Black Friday,0,2004,143,Action|Crime|Drama,8.5,16761,A dramatic presentation of the bomb blasts tha...,Black Friday is a film about the investigation...,The story of the Bombay bomb blasts,Kay Kay Menon|Pavan Malhotra|Aditya Srivastava...,3 nominations,9 February 2007 (India)
1188,Omkara (2006 film),tt0488414,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Omkara_(2006_film),Omkara,Omkara,0,2006,155,Action|Crime|Drama,8.1,17594,Advocate Raghunath Mishra has arranged the mar...,A politically-minded enforcer's misguided trus...,NaN,Ajay Devgn|Saif Ali Khan|Vivek Oberoi|Kareena ...,19 wins & 20 nominations,28 July 2006 (USA)
1293,Sarkar (2005 film),tt0432047,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sarkar_(2005_film),Sarkar,Sarkar,0,2005,124,Action|Crime|Drama,7.6,14694,Meet Subhash Nagre - a wealthy and influential...,The authority of a man who runs a parallel go...,'There are no Rights and Wrongs. Only Power' -...,Amitabh Bachchan|Abhishek Bachchan|Kay Kay Men...,2 wins & 10 nominations,1 July 2005 (India)
1294,Sehar,tt0477857,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sehar,Sehar,Sehar,0,2005,125,Action|Crime|Drama,7.8,1861,At the tender age of 8 Ajay Kumar is traumatiz...,Ajay Kumar the newly appointed honest SSP of ...,NaN,Arshad Warsi|Pankaj Kapur|Mahima Chaudhry|Sush...,NaN,29 July 2005 (India)
1361,Lakshya (film),tt0323013,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lakshya_(film),Lakshya,Lakshya,0,2004,186,Action|Drama|Romance,7.9,18777,Karan is a lazy good-for-nothing who lives on ...,An aimless jobless irresponsible grown man j...,It took him 24 years and 18000 feet to find hi...,Hrithik Roshan|Preity Zinta|Amitabh Bachchan|O...,4 wins & 10 nominations,18 June 2004 (USA)
1432,Gangaajal,tt0373856,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangaajal,Gangaajal,Gangaajal,0,2003,157,Action|Crime|Drama,7.8,14295,An SP Amit Kumar who is given charge of Tezpur...,An IPS officer motivates and leads a dysfuncti...,NaN,Ajay Devgn|Gracy Singh|Mohan Joshi|Yashpal Sha...,4 wins & 29 nominations,29 August 2003 (India)
1495,Company (film),tt0296574,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Company_(film),Company,Company,0,2002,155,Action|Crime|Drama,8.0,13474,Mallik is a henchman of Aslam Bhai a Mumbai u...,A small-time gangster named Chandu teams up wi...,A law & order enterprise,Ajay Devgn|Mohanlal|Manisha Koirala|Seema Bisw...,16 wins & 9 nominations,15 April 2002 (India)
1554,The Legend of Bhagat Singh,tt0319736,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Legend_of_Bh...,The Legend of Bhagat Singh,The Legend of Bhagat Singh,0,2002,155,Action|Biography|Drama,8.1,13455,Bhagat was born in British India during the ye...,The story of a young revolutionary who raised ...,NaN,Ajay Devgn|Sushant Singh|D. Santosh|Akhilendra...,11 wins & 5 nominations,7 June 2002 (India)
1607,Nayak (2001 Hindi film),tt0291376,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Nayak_(2001_Hind...,Nayak: The Real Hero,Nayak: The Real Hero,0,2001,187,Action|Drama|Thriller,7.8,12522,Employed as a camera-man at a popular televisi...,A man accepts a challenge by the chief ministe...,Fight the power,Anil Kapoor|Rani Mukerji|Amrish Puri|Johnny Le...,2 nominations,7 September 2001 (India)

In [ ]:
# write a function that can return the track record of 2 teams against each other

### Adding new cols

In [ ]:
# completely new
movies['Country'] = 'India'
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),India
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),India

In [ ]:
# from existing ones
movies.dropna(inplace=True)

In [ ]:
movies['lead actor'] = movies['actors'].str.split('|').apply(lambda x:x[0])
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country,lead actor
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA),India,Ranveer Singh
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India),India,Gavie Chahal
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA),India,Ayushmann Khurrana
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA),India,Sidharth Malhotra
96,Raid (2018 film),tt7363076,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raid_(2018_film),Raid,Raid,0,2018,122,Action|Crime|Drama,7.4,13159,Set in the 80s in Uttar Pradesh India Raid i...,A fearless income tax officer raids the mansio...,Heroes don't always come in uniform,Ajay Devgn|Saurabh Shukla|Ileana D'Cruz|Amit S...,2 wins & 3 nominations,16 March 2018 (India),India,Ajay Devgn

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 298 entries, 11 to 1623
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           298 non-null    object
 1   imdb_id           298 non-null    object
 2   poster_path       298 non-null    object
 3   wiki_link         298 non-null    object
 4   title_y           298 non-null    object
 5   original_title    298 non-null    object
 6   is_adult          298 non-null    int64
 7   year_of_release   298 non-null    int64
 8   runtime           298 non-null    object
 9   genres            298 non-null    object
 10  imdb_rating       298 non-null    float64
 11  imdb_votes        298 non-null    int64
 12  story             298 non-null    object
 13  summary           298 non-null    object
 14  tagline           298 non-null    object
 15  actors            298 non-null    object
 16  wins_nominations  298 non-null    object
 17  release_date      298 non-null    object
 18  Country           298 non-null    object
dtypes: float64(1), int64(3), object(15)
memory usage: 46.6+ KB

### Important DataFrame Functions

In [ ]:
# astype
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [ ]:
ipl['ID'] = ipl['ID'].astype('int32')

In [ ]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int32(1), object(18)
memory usage: 144.9+ KB

In [ ]:
ipl['Season'] = ipl['Season'].astype('category')
ipl['Team1'] = ipl['Team1'].astype('category')
ipl['Team2'] = ipl['Team2'].astype('category')

In [ ]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    category
 6   Team2            950 non-null    category
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: category(3), float64(1), int32(1), object(15)
memory usage: 127.4+ KB

In [ ]:
# find which player has won most potm -> in finals and qualifiers

In [ ]:
# Toss decision plot

In [ ]:
# how many matches each team has played